CREATE DOMAIN KILOMETER AS NUMERIC CHECK (VALUE >= 0);

CREATE DOMAIN LITER AS NUMERIC CHECK (VALUE >= 0);

CREATE TABLE VEHICLE (
	ID SERIAL NOT NULL PRIMARY KEY,
	LICENSEPLATE VARCHAR(20),
	MAKE VARCHAR(10),
	MODEL VARCHAR(20),
	MOTORNUMBER BIGINT,
	KILOMETERS PUBLIC.KILOMETER,
	ISOPERATIONAL BOOLEAN,
	OPERATIONSTART TIMESTAMP,
	LASTSERVICE TIMESTAMP,
	GASCONSUMPTION PUBLIC.LITER,
	MAXKILOMETERS PUBLIC.KILOMETER,
	PRICEPERKILOMETER MONEY,
	PRICEPERHOUR MONEY
);

CREATE TABLE MOTORCAR (CHILDSEAT BOOLEAN, EXTRAS VARCHAR(30) ARRAY) INHERITS (VEHICLE);

CREATE TABLE COMPACTCAR (
	PRICEPERKILOMETER MONEY DEFAULT 2,
	PRICEPERHOUR MONEY DEFAULT 10,
	MAXKILOMETERS PUBLIC.KILOMETER DEFAULT 1000000,
	EXTRAS VARCHAR(30) ARRAY DEFAULT ARRAY['airconditioning', 'stereo', 'gps']
) INHERITS (MOTORCAR);

CREATE TABLE LIMOUSINE (
	PRICEPERKILOMETER MONEY DEFAULT 5,
	PRICEPERHOUR MONEY DEFAULT 100,
	MAXKILOMETERS PUBLIC.KILOMETER DEFAULT 200000,
	EXTRAS VARCHAR(30) ARRAY DEFAULT ARRAY[
		'airconditioning',
		'stereo',
		'gps',
		'fridge',
		'sofa'
	]
) INHERITS (MOTORCAR);

CREATE TABLE CONVERTIBLE (
	BACKSEAT BOOLEAN,
	PRICEPERKILOMETER MONEY DEFAULT 1,
	PRICEPERHOUR MONEY DEFAULT 5,
	MAXKILOMETERS PUBLIC.KILOMETER DEFAULT 50000,
	EXTRAS VARCHAR(30) ARRAY DEFAULT ARRAY['airconditioning', 'stereo']
) INHERITS (MOTORCAR);

CREATE TABLE SEDAN (
	PRICEPERKILOMETER MONEY DEFAULT 1.5,
	PRICEPERHOUR MONEY DEFAULT 5.5,
	MAXKILOMETERS PUBLIC.KILOMETER DEFAULT 500000,
	EXTRAS VARCHAR(30) ARRAY DEFAULT ARRAY['airconditioning', 'stereo', 'tv']
) INHERITS (MOTORCAR);

CREATE TABLE STATIONWAGON (
	LOADINGVOLUME INT,
	PRICEPERKILOMETER MONEY DEFAULT 2.5,
	PRICEPERHOUR MONEY DEFAULT 55.5,
	MAXKILOMETERS PUBLIC.KILOMETER DEFAULT 120000,
	EXTRAS VARCHAR(30) ARRAY DEFAULT ARRAY['airconditioning', 'stereo', 'bed']
) INHERITS (MOTORCAR);

CREATE TABLE VAN (
	NUMBEROFSEATS INT,
	PRICEPERKILOMETER MONEY DEFAULT 1.25,
	PRICEPERHOUR MONEY DEFAULT 25.5,
	MAXKILOMETERS PUBLIC.KILOMETER DEFAULT 200000,
	EXTRAS VARCHAR(30) ARRAY DEFAULT ARRAY['airconditioning', 'stereo', 'bed', 'bikeHolder']
) INHERITS (MOTORCAR);

CREATE TABLE TRUCK (MAXLOAD BIGINT) INHERITS (VEHICLE);

CREATE TABLE PICKUP (
	PRICEPERKILOMETER MONEY DEFAULT 10.25,
	PRICEPERHOUR MONEY DEFAULT 500,
	MAXKILOMETERS PUBLIC.KILOMETER DEFAULT 50000
) INHERITS (TRUCK);

CREATE TABLE TRANSPORTER (
	PRICEPERKILOMETER MONEY DEFAULT 15.25,
	PRICEPERHOUR MONEY DEFAULT 1000,
	MAXKILOMETERS PUBLIC.KILOMETER DEFAULT 75000,
	HEIGHT BIGINT
) INHERITS (TRUCK);

ALTER TABLE VEHICLE
ADD COLUMN IMAGE BYTEA;

ALTER TABLE COMPACTCAR
ALTER COLUMN IMAGE
SET DEFAULT DECODE('89504e470d0a1a0a', 'hex');

-- PNG
ALTER TABLE LIMOUSINE
ALTER COLUMN IMAGE
SET DEFAULT DECODE('ffd8ffe000104a46', 'hex');

ALTER TABLE CONVERTIBLE
ALTER COLUMN IMAGE
SET DEFAULT DECODE('4749463839612602', 'hex');

ALTER TABLE SEDAN
ALTER COLUMN IMAGE
SET DEFAULT DECODE('255044462d312e34', 'hex');

ALTER TABLE STATIONWAGON
ALTER COLUMN IMAGE
SET DEFAULT DECODE('504b030414000000', 'hex');

ALTER TABLE VAN
ALTER COLUMN IMAGE
SET DEFAULT DECODE('377abcaf271c', 'hex');

ALTER TABLE PICKUP
ALTER COLUMN IMAGE
SET DEFAULT DECODE('526172211a0700', 'hex');

ALTER TABLE TRANSPORTER
ALTER COLUMN IMAGE
SET DEFAULT DECODE('424d3e0000000000', 'hex');